name = "BolometricCorrections"
uuid = "37ee4594-8306-40da-a4c2-d7ed95560e0b"
authors = ["cgarling <chris.t.garling@gmail.com>"]
version = "0.1.5"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CodecXz = "ba30903b-d9e8-5048-a5ec-d1f5b0d4b47b"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
ArgCheck = "1, 2"
CSV = "0.10"
CodecXz = "0.7"
Compat = "3.47, 4.10"
DataDeps = "0.7"
Documenter = "1"
FITSIO = "0.17.5"
Git = "1.5"
Interpolations = "0.15, 0.16"
Printf = "<0.0.1, 1"
SafeTestsets = "0.1"
Scratch = "1"
StaticArrays = "1"
StatsBase = "0.32, 0.33, 0.34"
Tables = "1"
Tar = "<0.0.1, 1"
Test = "<0.0.1, 1"
TypedTables = "1"
Unicode = "<0.0.1, 1"
julia = "1.7"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"

[targets]
test = ["Documenter", "SafeTestsets", "Test", "TypedTables"]
